sudo: false

language: node_js

addons:
  chrome: stable

env:
  - MOZ_HEADLESS=1

script: npm run lint && npm run test-server-open && npm run test-node && npm run test-browser
after_script: npm run test-server-close

node_js:
  - "10"
  - "12"
  - "14"
  - "node"

cache:
  directories:
    - node_modules
    - $HOME/.npm

deploy:
  provider: npm
  edge: true
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    node: "node"
